---

# - name: Print facts
#  debug: var=ansible_facts

# docker run \
#  --volume=/:/rootfs:ro \
#  --volume=/var/run:/var/run:ro \
#  --volume=/sys:/sys:ro \
#  --volume=/var/lib/docker/:/var/lib/docker:ro \
#  --volume=/dev/disk/:/dev/disk:ro \
#  --publish=8080:8080 \
#  --detach=true \
#  --name=cadvisor \
#  google/cadvisor:latest

# - name: example copying file with owner and permissions
#  copy:
#    src: ../../
#    dest: /root/server-atomic/
#    directory_mode: true
#    force: true

# - name: Print debug info
#  debug:
#    msg:
#      ansible_distribution: "{{ ansible_distribution }}"
#      ansible_distribution_version: "{{ ansible_distribution_version }}"
#      ansible_product_uuid: "{{ ansible_product_uuid }}"
#      inventory_hostname: "{{ inventory_hostname }}"
#      ansible_default_ipv4: "{{ ansible_default_ipv4 }}"

# - name: Display all variables/facts known for a host
#   debug:
#     var: hostvars[inventory_hostname]
#   tags: debug_info

#- name: Add epel repo to host
#  command: "rpm-ostree install epel-release"
#  args:
#    creates: "/etc/yum.repos.d/epel.repo"
#  register: result

#- name: Add centos-release-openshift-origin repo to host
#  command: "rpm-ostree install centos-release-openshift-origin"
#  args:
#    creates: "/etc/yum.repos.d/CentOS-OpenShift-Origin.repo"
#  register: result

# - name: Reboot after centos-openshift-origin was added
#   reboot:
#- name: Install etcd
#  command: "rpm-ostree install etcd"
#  register: result
#  ignore_errors: yes
