---

- name: create users
  user:
    name: "{{ item }}"
    groups:
      - wheel
      - docker
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_file: .ssh/id_rsa
  with_items: "{{ github_users }}"

- name: set authorized keys taken from github
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "https://github.com/{{ item }}.keys"
  with_items: "{{ github_users }}"
