---

- name: install tool packages
  command: "rpm-ostree install --idempotent {{ tool_packages | join(' ') }}"
  register: res_install

- name: reboot after tool packages instalation if needed
  reboot:
  when: res_install is changed and res_install.stdout.find('systemctl reboot') != -1
