---

- name: Print facts
  debug: var=ansible_facts

- name: Print debug info
  debug:
    msg:
      ansible_distribution: "{{ ansible_distribution }}"
      ansible_distribution_version: "{{ ansible_distribution_version }}"
      ansible_product_uuid: "{{ ansible_product_uuid }}"
      inventory_hostname: "{{ inventory_hostname }}"
      ansible_default_ipv4: "{{ ansible_default_ipv4 }}"

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: debug_info
