---

- name: create data directory for docker registry
  file:
    path: "{{ docker_registry_path }}"
    state: directory
    owner: root
    group: docker
    mode: 0775
    recurse: yes

- name: fix docker registry selinux rights
  command: "chcon -Rvt svirt_sandbox_file_t {{ docker_registry_path }}"

- name: create docker-registry.service
  template:
    src: etc/systemd/system/docker-registry.service
    dest: /etc/systemd/system/docker-registry.service
    owner: root
    group: root
    mode: 0644

- name: ensure docker-registry service is started and enabled
  systemd:
    daemon_reload: true
    name: docker-registry
    state: restarted
    enabled: true

- name: use local docker registry
  template:
    src: etc/sysconfig/docker
    dest: /etc/sysconfig/docker
    owner: root
    group: root
    mode: 0644
