---

# - name: example copying file with owner and permissions
#  copy:
#    src: ../../
#    dest: /root/server-atomic/
#    directory_mode: true
#    force: true

- name: lower raid sync priority
  command: "sysctl -w dev.raid.speed_limit_max=1000"

- name: create /etc/sysctl.conf
  template:
    src: etc/sysctl.conf
    dest: /etc/sysctl.conf
    owner: root
    group: root
    mode: 0644

- name: create /etc/sysctl.d/00-sysctl.conf
  template:
    src: etc/sysctl.d/00-sysctl.conf
    dest: /etc/sysctl.d/00-sysctl.conf
    owner: root
    group: root
    mode: 0644

- name: create /etc/sysctl.d/99-sysctl.conf
  template:
    src: etc/sysctl.d/99-sysctl.conf
    dest: /etc/sysctl.d/99-sysctl.conf
    owner: root
    group: root
    mode: 0644
