---

- name: install etcd
  command: "atomic install --system --system-package=no --storage=ostree --name=etcd registry.fedoraproject.org/latest/etcd"
  register: result

- name: reload systemd daemon
  command: "systemctl daemon-reload"
  register: result

- name: copy etcd.conf
  template:
    src: etcd.conf.j2
    dest: /etc/etcd/etcd.conf
    owner: root
    group: root
    mode: 0644

- name: enable etcd
  command: "systemctl enable etcd"

- name: start etcd
  command: "systemctl start etcd"


- name: download easy-rsa.tar.gz
  get_url:
    url: https://storage.googleapis.com/kubernetes-release/easy-rsa/easy-rsa.tar.gz
    dest: ./easy-rsa.tar.gz
    mode: 0440

- name: extract easy-rsa.tar.gz into ./easy-rsa
  unarchive:
    remote_src: true
    src: ./easy-rsa.tar.gz
    dest: ./

- name: init-pki
  command: "./easyrsa init-pki"
  args:
    chdir: ./easy-rsa-master/easyrsa3/
    creates: /root/easy-rsa-master/easyrsa3/pki

- name: build-ca
  command: './easyrsa --batch "--req-cn=127.0.0.1@`date +%s`" build-ca nopass'
  args:
    chdir: ./easy-rsa-master/easyrsa3/
    creates: /root/easy-rsa-master/easyrsa3/pki/private/ca.key

- name: build-server-full
  command: './easyrsa --subject-alt-name="IP:127.0.0.1" build-server-full server nopass'
  args:
    chdir: ./easy-rsa-master/easyrsa3/
    creates: /root/easy-rsa-master/easyrsa3/pki/reqs/server.req
