---

- name: create grafana.service
  template:
    src: etc/systemd/system/grafana.service.j2
    dest: /etc/systemd/system/grafana.service
    owner: root
    group: root
    mode: 0644

- name: ensure grafana service is started and enabled
  systemd:
    daemon_reload: true
    name: grafana
    state: restarted
    enabled: true

