---
- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- include: preflight.yml
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- include: install.yml
  tags:
    - prometheus_install

- include: configure.yml
  tags:
    - prometheus_configure

- name: ensure prometheus service is started and enabled
  systemd:
    daemon_reload: true
    name: prometheus
    state: restarted
    enabled: true
  tags:
    - prometheus_run
