- hosts: all
  become: yes
  gather_facts: yes
  remote_user: root
  debugger: never # always | never | on_failed | on_unreachable | on_skipped
  roles:
    # - core
    # - os
    # - cockpit
    # - tools
    # - persistence
    # - docker
    # - docker-registry
    # - etcd
    - flannel
    # -----
    - kubernetes-core
    - kubernetes-client
    - kubernetes-master
    - kubernetes-node
    # -----
    # - desktop-gnome3
    # - desktop-kde
    # - desktop-xfce
    # -----
    # - users
