- hosts: all
  become: yes
  gather_facts: yes
  remote_user: root
  debugger: never # always | never | on_failed | on_unreachable | on_skipped
  roles:
    - info
    - os
    - os-update
    - core
    - docker
    - docker-registry # <--- service
    - users
    - firewall
    - fail2ban
    - ssh
    - cockpit
    - tools
    - tuned
#    - graphite
#    - grafana
#    - persistence
#    - etcd
#    - flannel
    - cadvisor
#    # - prometheus
#    # -----
#    - kubernetes-core
#    - kubernetes-client
#    - kubernetes-master
#    - kubernetes-node
#    # -----
#    # - desktop-gnome3
#    # - desktop-kde
    - desktop-enlightenment
    - desktop-xfce
