- hosts: all
  become: yes
  gather_facts: yes
  remote_user: root
  debugger: never # always | never | on_failed | on_unreachable | on_skipped
  roles:
    - core
    # - os
    - docker
    - tools
    # - cockpit
    # - desktop-kde
    - desktop-xfce
    # - skopeo
    - users
