---

#- name: Copy sources
#  synchronize:
#    src: ./../../../../
#    dest: /root/server-atomic
#    recursive: true
#    delete: false

- name: Upgrade the atomic host platform to the latest version (atomic host upgrade)
  atomic_host:
    revision: latest

#- name: Add epel repo to host
#  command: "rpm-ostree install epel-release"
#  args:
#    creates: "/etc/yum.repos.d/epel.repo"
#  register: result

#- name: Add centos-release-openshift-origin repo to host
#  command: "rpm-ostree install centos-release-openshift-origin"
#  args:
#    creates: "/etc/yum.repos.d/CentOS-OpenShift-Origin.repo"
#  register: result

# - name: Reboot after centos-openshift-origin was added
#   reboot:

#- name: Install mc
#  command: "rpm-ostree install mc"
#  register: result
#  ignore_errors: yes
#
#- name: Install mosh
#  command: "rpm-ostree install mosh"
#  register: result
#  ignore_errors: yes
#
#- name: Install kubernetes-master
#  command: "rpm-ostree install kubernetes-master"
#  register: result
#  ignore_errors: yes
#
#- name: Install kubernetes-node
#  command: "rpm-ostree install kubernetes-node"
#  register: result
#  ignore_errors: yes
#
#- name: Install kubernetes-client
#  command: "rpm-ostree install kubernetes-client"
#  register: result
#  ignore_errors: yes
#
#- name: Install kubernetes
#  command: "rpm-ostree install kubernetes"
#  register: result
#  ignore_errors: yes
#
#- name: Install flannel
#  command: "rpm-ostree install flannel"
#  register: result
#  ignore_errors: yes
#
#- name: Install etcd
#  command: "rpm-ostree install etcd"
#  register: result
#  ignore_errors: yes
#
##- name: Install kubeadm
##  command: "atomic install --system --name kubelet docker.io/jasonbrooks/kubeadm"
##  register: result
##  ignore_errors: yes
#
##- name: Install collectd
##  command: "rpm-ostree install collectd collectd-lvm rrdtool rrdtool-devel"
##  register: result
##  ignore_errors: yes
#
#
#
#- name: Reboot after cockpit install
#  reboot:
#  when: result is succeeded
#
###
################
###
#
##- name: Install cockpit
##  atomic_container:
##    name: cockpit
##    image: cockpit/ws
##    state: latest
##    backend: ostree
#
##- name: Reload unit files
##  command: systemctl daemon-reload
#
##- name: Enable and start cockpit
##  service:
##    name: cockpit
##    enabled: yes
##    state: restarted
